# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_PACKAGES_USERID: ${{ secrets.PACKAGES_USERID }}
          GITHUB_PACKAGES_IMPORT_TOKEN: ${{ secrets.PACKAGES_IMPORT_TOKEN }}